### ISSUE TITLE
On-chain verifiability of a passed baton, for the purposes of DKG Alice-Bobs

### ISSUE THREAD

**Issue by jMyles** [threshold-network/threshold#3]
In conversation today with @beaushinkle, we outlined the following situation:

* An `Alice` (understood loosely; application authority, be it tPRE, tECDSA, or another primitive) performs the granting action on the network.  At this time, rather than the relevant secret material being enshrined directly (eg, kfrags encrypted for a specific Ursula / HD scheme), we imagine that an `AbioticAlice` (to be clear: a separate, helper Alice) grants access to members of the cohort.
* If the health of the cohort begins to falter, this `HelperAbioticAlice` will revoke access to a dead / slashed Ursula-operator and grant to a new one.
* But what about a bad behaving Ursula-operator who doesn't delete the material and then resumes protocol activity?  To combat this, we add the appropriate proof to Bob's journey (for example, proof in the `Capsule` showing that the updated cohort performed the operation, excluding the revoked nodes), and allow Bob (or anyone, really) to publish this information on-chain.
* Unresolved question: What if Bob is in on the trick?  Seems plausible in the tbtcv2 scenario.

**Comment by beaushinkle** [comment]
For context, here was my motivating question.

Right now, tbtcv2 has a "baton pass" that occurs when a wallet fails a heartbeat (as in, becomes at risk of not having enough operators to sign messages). So after failing the heartbeat, but while still being able to transfer funds, the protocol tells the operators they must move the remaining funds in their wallet to another wallet.

This costs btc for the mining fee, and eth for the spv proof gas. I was wondering if instead, we could transfer ownership of the underlying ecdsa key material from some set of operators to some other set, and then be able to prove that this transfer happened. I was further wondering if this transfer of key material was cheaper than the original bitcoin transfer scheme.

**Comment by beaushinkle** [comment]
@jMyles are you okay closing this? if we're not okay just out-right closing, maybe we can put the idea/conversation somewhere
