### ISSUE TITLE
Out of date `Conditions.Condition properties`

### ISSUE THREAD

**Issue by ghardin1314** [threshold-network/threshold#9]
https://github.com/threshold-network/threshold/blob/f6aa88f6993487b22c1ca388ee02edb69ff7ce9d/docs/app-development/threshold-access-control-tac/advanced-usage/implementing-revocation-via-smart-contract.md?plain=1#L27-L28

should be: 

`functionName` -> `method`
`functionParams` -> `parameters`

**Comment by theref** [comment]
@ghardin1314 Thank you so much, the issues you've been raising are so helpful. I've submitted a fix for this

**Comment by derekpierre** [comment]
@theref , merged your changes (https://app.gitbook.com/o/R2meumXNNad4y1B10iL7/s/WosjlL4zUGUMlcMfuSAp/~/changes/wdqkHVidSPhDlc5kyTxQ/).
